version: '3.8'

services:
  db:
    container_name: autosphere_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_autosphere:/var/lib/postgresql/data
volumes:
  db_data_autosphere:
